"""Read-only audit of where every marker's scoring range comes from.

    python ranges_audit.py            # print the table
    python ranges_audit.py --write    # regenerate docs/ranges_audit.md

Sources, per marker and sex:
  CellDeep-calibrated   the threshold in markers_reference.py
  Lab-printed fallback  no CellDeep threshold; scored against the range the lab printed for that
                        result (pipeline.score_and_build_record), unscored when none is printed
  Missing               no CellDeep threshold and no lab fallback possible
  Not scored            lab_reported.py tests: shown with the lab's range and flag only

Nothing here invents a threshold: every gap is marked "clinic input needed".
"""

import argparse
from pathlib import Path

import lab_reported
from markers_reference import MARKER_LIBRARY, has_missing_thresholds, resolve_marker_config

DOC = Path(__file__).resolve().parent.parent / "docs" / "ranges_audit.md"
SEXES = ("male", "female")
CLINIC = "clinic input needed"


def _threshold(cfg):
    if cfg["kind"] == "categorical":
        return "categorical (expected/unexpected result)"
    return cfg.get("disp_range") or ""


def marker_rows():
    rows = []
    for name, config in MARKER_LIBRARY.items():
        cells = {}
        for sex in SEXES:
            cfg = resolve_marker_config(name, config, sex)
            if not has_missing_thresholds(cfg):
                cells[sex] = f"CellDeep-calibrated: {_threshold(cfg)}"
            elif cfg["kind"] == "range":
                cells[sex] = f"Lab-printed fallback; unscored if no lab range - {CLINIC}"
            else:
                cells[sex] = f"Missing - {CLINIC}"
        notes = []
        if name in {"Estradiol", "Progesterone", "Free Testosterone", "SHBG"}:
            notes.append("female + explicit postmenopausal BHRT in the note: CellDeep BHRT target")
        if config.get("suppress_low_on_trt"):
            notes.append("low values not flagged when the note states TRT")
        if config.get("default_sex"):
            notes.append(f"sex not entered: uses the {config['default_sex']} column")
        rows.append((name, config["category"], config["kind"], cells["male"], cells["female"], "; ".join(notes)))
    return rows


def missing(sex):
    """Markers with no CellDeep threshold for this sex."""
    return [name for name, config in MARKER_LIBRARY.items()
            if has_missing_thresholds(resolve_marker_config(name, config, sex))]


def render():
    lines = [
        "# Ranges and thresholds audit",
        "",
        "Generated by `celldeep-tool/ranges_audit.py --write`; do not edit by hand. A test fails when this",
        "file and `markers_reference.py` / `lab_reported.py` disagree.",
        "",
        "Sources: **CellDeep-calibrated** (threshold in `markers_reference.py`), **Lab-printed fallback**",
        "(no CellDeep threshold, so the result is scored against the range the lab printed for it, and",
        "left unscored when the lab printed none), **Missing**, and **Not scored** (shown with the lab's",
        "own range and H/L flag only). No threshold is invented; every gap needs clinic input.",
        "",
        "## Missing CellDeep thresholds",
        "",
        f"- Male: {', '.join(missing('male')) or 'none'}",
        f"- Female: {', '.join(missing('female')) or 'none'}",
        "",
        "## Scored markers (`markers_reference.py`)",
        "",
        "| Marker | Category | Kind | Male | Female | Notes |",
        "|---|---|---|---|---|---|",
    ]
    lines += [f"| {' | '.join(row)} |" for row in marker_rows()]
    lines += [
        "",
        "## Lab-reported, not scored (`lab_reported.py`)",
        "",
        "Shown with the printed lab range and the lab's own H/L flag. No CellDeep score until the clinic",
        "supplies thresholds.",
        "",
        "| Test | Group | Source |",
        "|---|---|---|",
    ]
    lines += [f"| {name} | {config['group']} | Not scored - {CLINIC} |"
              for name, config in lab_reported.LAB_REPORTED_LIBRARY.items()]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help=f"write {DOC}")
    args = parser.parse_args()
    text = render()
    if args.write:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        DOC.write_text(text, encoding="utf-8")
    print(text, end="")


if __name__ == "__main__":
    main()
